import { TestCategory, Test, TestDimension, TestQuestion, TestOption, TestResult } from './types';

export const testCategories: TestCategory[] = [
  {
    id: 'cat-1',
    name: '人格类型',
    slug: 'personality',
    description: '探索你的人格特质与行为模式',
    icon: '🧠',
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 'cat-2',
    name: '情感关系',
    slug: 'relationship',
    description: '了解你的爱情风格与关系模式',
    icon: '💫',
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 'cat-3',
    name: '职业发展',
    slug: 'career',
    description: '发现你的职业优势与潜在方向',
    icon: '🌟',
    color: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'cat-4',
    name: '情绪心理',
    slug: 'emotion',
    description: '认识你的情绪反应与心理模式',
    icon: '🌊',
    color: 'from-teal-500 to-emerald-600',
  },
];

export const tests: Test[] = [
  {
    id: 'test-mbti',
    title: '16型人格风格测试',
    slug: 'personality-16-types',
    description: '基于心理偏好理论，探索你在能量来源、信息感知、决策方式和生活态度四个维度上的独特风格，揭示你是哪种类型的人。',
    shortDescription: '探索你的16种人格类型，了解你独特的思维与行为模式',
    categoryId: 'cat-1',
    questionCount: 30,
    estimatedMinutes: 10,
    tags: ['人格', '经典', '热门'],
    completionCount: 128463,
    isPopular: true,
    isFeatured: true,
    coverGradient: 'from-violet-600 via-purple-600 to-indigo-700',
    createdAt: '2024-01-01',
  },
  {
    id: 'test-bigfive',
    title: '大五人格测试',
    slug: 'big-five',
    description: '大五人格模型（OCEAN）是心理学中最具科学基础的人格模型之一，通过五个核心维度全面描绘你的人格图谱。',
    shortDescription: '通过开放性、责任心等五大维度，绘制你的人格全貌',
    categoryId: 'cat-1',
    questionCount: 25,
    estimatedMinutes: 8,
    tags: ['人格', '科学', '深度'],
    completionCount: 87234,
    isPopular: true,
    isFeatured: true,
    coverGradient: 'from-blue-600 via-indigo-600 to-violet-700',
    createdAt: '2024-01-15',
  },
  {
    id: 'test-career',
    title: '职业倾向测试',
    slug: 'career-tendency',
    description: '基于职业兴趣与能力倾向理论，帮助你发现最适合自己天赋与热情的职业方向，为职业规划提供洞见。',
    shortDescription: '发现你的职业天赋，找到最适合你的工作方向',
    categoryId: 'cat-3',
    questionCount: 28,
    estimatedMinutes: 10,
    tags: ['职业', '规划', '实用'],
    completionCount: 65891,
    isPopular: true,
    isFeatured: false,
    coverGradient: 'from-cyan-600 via-blue-600 to-indigo-600',
    createdAt: '2024-02-01',
  },
  {
    id: 'test-love',
    title: '爱情依恋风格测试',
    slug: 'attachment-style',
    description: '探索你在亲密关系中的依恋模式——你是安全型、焦虑型还是回避型？了解你的关系风格，能帮助你建立更健康的连结。',
    shortDescription: '了解你的依恋风格，让亲密关系更深入、更安全',
    categoryId: 'cat-2',
    questionCount: 20,
    estimatedMinutes: 7,
    tags: ['关系', '依恋', '情感'],
    completionCount: 54327,
    isPopular: false,
    isFeatured: true,
    coverGradient: 'from-rose-500 via-pink-500 to-purple-600',
    createdAt: '2024-02-15',
  },
  {
    id: 'test-stress',
    title: '压力应对风格测试',
    slug: 'stress-style',
    description: '你面对压力时是战斗、逃跑还是冻结？本测试帮助你了解自己的压力应对机制，以及如何更有效地管理压力。',
    shortDescription: '发现你在压力下的真实反应模式与应对策略',
    categoryId: 'cat-4',
    questionCount: 22,
    estimatedMinutes: 8,
    tags: ['压力', '情绪', '成长'],
    completionCount: 43218,
    isPopular: false,
    isFeatured: false,
    coverGradient: 'from-teal-500 via-emerald-500 to-cyan-600',
    createdAt: '2024-03-01',
  },
  {
    id: 'test-enneagram',
    title: '九型人格测试',
    slug: 'enneagram',
    description: '九型人格是一套古老而深刻的人格系统，揭示我们内心最深处的动机、恐惧与渴望，帮助我们走向真正的自我整合。',
    shortDescription: '探索你的核心动机与内心渴望，发现真实的自我',
    categoryId: 'cat-1',
    questionCount: 36,
    estimatedMinutes: 12,
    tags: ['人格', '深度', '成长'],
    completionCount: 38965,
    isPopular: false,
    isFeatured: false,
    coverGradient: 'from-amber-500 via-orange-500 to-rose-600',
    createdAt: '2024-03-15',
  },
  {
    id: 'test-sbti',
    title: 'SBTI 人格测试',
    slug: 'sbti',
    description: '2026年4月爆火全网的神奇人格测试，全称"Silly Big Personality Test（傻乎乎的大人格测试）"。31道荒诞接地气的题目，测出你最真实的"阴暗面"与生存姿态。仅供娱乐，别当诊断。',
    shortDescription: '全网爆火的魔性测试，31道题揭秘你最真实的生存姿态',
    categoryId: 'cat-1',
    questionCount: 31,
    estimatedMinutes: 5,
    tags: ['爆火', '娱乐', '自嘲'],
    completionCount: 892314,
    isPopular: true,
    isFeatured: true,
    coverGradient: 'from-yellow-500 via-orange-500 to-red-600',
    createdAt: '2026-04-10',
  },
];

// ==== 16-Type Personality Test Data ====
export const mbtiDimensions: TestDimension[] = [
  { id: 'dim-ei', testId: 'test-mbti', name: '能量来源', description: '你从哪里获得能量', minLabel: '内倾 (I)', maxLabel: '外倾 (E)', color: '#8b5cf6' },
  { id: 'dim-sn', testId: 'test-mbti', name: '信息感知', description: '你如何接收和处理信息', minLabel: '实感 (S)', maxLabel: '直觉 (N)', color: '#06b6d4' },
  { id: 'dim-tf', testId: 'test-mbti', name: '决策方式', description: '你如何做出决策', minLabel: '情感 (F)', maxLabel: '思考 (T)', color: '#10b981' },
  { id: 'dim-jp', testId: 'test-mbti', name: '生活态度', description: '你如何安排自己的生活', minLabel: '知觉 (P)', maxLabel: '判断 (J)', color: '#f59e0b' },
];

export const mbtiQuestions: TestQuestion[] = [
  { id: 'q1', testId: 'test-mbti', text: '在社交聚会之后，你通常感到…', order: 1, dimensionId: 'dim-ei' },
  { id: 'q2', testId: 'test-mbti', text: '当需要做重要决定时，你更倾向于…', order: 2, dimensionId: 'dim-tf' },
  { id: 'q3', testId: 'test-mbti', text: '面对新项目，你更喜欢先了解…', order: 3, dimensionId: 'dim-sn' },
  { id: 'q4', testId: 'test-mbti', text: '你的日程安排通常是…', order: 4, dimensionId: 'dim-jp' },
  { id: 'q5', testId: 'test-mbti', text: '和陌生人交谈，你感觉…', order: 5, dimensionId: 'dim-ei' },
  { id: 'q6', testId: 'test-mbti', text: '处理问题时，你更看重…', order: 6, dimensionId: 'dim-tf' },
  { id: 'q7', testId: 'test-mbti', text: '你更容易被哪种信息吸引…', order: 7, dimensionId: 'dim-sn' },
  { id: 'q8', testId: 'test-mbti', text: '对于截止日期，你通常…', order: 8, dimensionId: 'dim-jp' },
  { id: 'q9', testId: 'test-mbti', text: '独处的时间对你来说…', order: 9, dimensionId: 'dim-ei' },
  { id: 'q10', testId: 'test-mbti', text: '在冲突中，你更倾向于…', order: 10, dimensionId: 'dim-tf' },
  { id: 'q11', testId: 'test-mbti', text: '你更信任哪种判断方式…', order: 11, dimensionId: 'dim-sn' },
  { id: 'q12', testId: 'test-mbti', text: '在工作或学习中，你喜欢…', order: 12, dimensionId: 'dim-jp' },
  { id: 'q13', testId: 'test-mbti', text: '一个理想的周末，你更可能…', order: 13, dimensionId: 'dim-ei' },
  { id: 'q14', testId: 'test-mbti', text: '当朋友倾诉烦恼时，你更倾向于…', order: 14, dimensionId: 'dim-tf' },
  { id: 'q15', testId: 'test-mbti', text: '你对未来的规划通常是…', order: 15, dimensionId: 'dim-sn' },
  { id: 'q16', testId: 'test-mbti', text: '对于计划被临时打乱，你的感受是…', order: 16, dimensionId: 'dim-jp' },
  { id: 'q17', testId: 'test-mbti', text: '结识新朋友，你通常…', order: 17, dimensionId: 'dim-ei' },
  { id: 'q18', testId: 'test-mbti', text: '评价一件事好不好，你更看重…', order: 18, dimensionId: 'dim-tf' },
  { id: 'q19', testId: 'test-mbti', text: '你更喜欢哪种工作方式…', order: 19, dimensionId: 'dim-sn' },
  { id: 'q20', testId: 'test-mbti', text: '面对开放式结局，你感到…', order: 20, dimensionId: 'dim-jp' },
  { id: 'q21', testId: 'test-mbti', text: '在团队中，你更喜欢的角色是…', order: 21, dimensionId: 'dim-ei' },
  { id: 'q22', testId: 'test-mbti', text: '当看到别人哭泣时，你的第一反应是…', order: 22, dimensionId: 'dim-tf' },
  { id: 'q23', testId: 'test-mbti', text: '你更容易被哪类内容打动…', order: 23, dimensionId: 'dim-sn' },
  { id: 'q24', testId: 'test-mbti', text: '做决定时，你倾向于…', order: 24, dimensionId: 'dim-jp' },
  { id: 'q25', testId: 'test-mbti', text: '在熟悉的环境里，你会…', order: 25, dimensionId: 'dim-ei' },
  { id: 'q26', testId: 'test-mbti', text: '争论时，你更在乎的是…', order: 26, dimensionId: 'dim-tf' },
  { id: 'q27', testId: 'test-mbti', text: '你更擅长哪种思维方式…', order: 27, dimensionId: 'dim-sn' },
  { id: 'q28', testId: 'test-mbti', text: '对于"即兴"活动，你的感受是…', order: 28, dimensionId: 'dim-jp' },
  { id: 'q29', testId: 'test-mbti', text: '当处于人群中时，你…', order: 29, dimensionId: 'dim-ei' },
  { id: 'q30', testId: 'test-mbti', text: '你如何看待"规则"这件事…', order: 30, dimensionId: 'dim-jp' },
];

type OptionsMap = Record<string, TestOption[]>;

export const mbtiOptions: OptionsMap = {
  q1: [
    { id: 'q1-a', questionId: 'q1', text: '精力充沛，享受社交带来的活力', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q1-b', questionId: 'q1', text: '还好，需要一点时间恢复', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q1-c', questionId: 'q1', text: '有些疲惫，更想一个人待着', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q2: [
    { id: 'q2-a', questionId: 'q2', text: '仔细分析利弊，依据逻辑推断', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q2-b', questionId: 'q2', text: '结合逻辑与感受综合考量', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q2-c', questionId: 'q2', text: '更多依赖内心感受与价值观', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q3: [
    { id: 'q3-a', questionId: 'q3', text: '整体方向和大局构想', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q3-b', questionId: 'q3', text: '两者兼顾，既看细节也看方向', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q3-c', questionId: 'q3', text: '具体的步骤和可操作细节', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q4: [
    { id: 'q4-a', questionId: 'q4', text: '有清晰的计划，按部就班执行', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q4-b', questionId: 'q4', text: '有大致方向，但保持弹性', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q4-c', questionId: 'q4', text: '随机应变，顺其自然', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
  q5: [
    { id: 'q5-a', questionId: 'q5', text: '轻松自然，我很享受', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q5-b', questionId: 'q5', text: '有点紧张，但可以应对', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q5-c', questionId: 'q5', text: '有些不适，更喜欢和熟人在一起', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q6: [
    { id: 'q6-a', questionId: 'q6', text: '客观公正，符合逻辑', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q6-b', questionId: 'q6', text: '兼顾情理，两者都重要', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q6-c', questionId: 'q6', text: '顾及他人感受，保持和谐', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q7: [
    { id: 'q7-a', questionId: 'q7', text: '充满想象力的可能性与未来展望', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q7-b', questionId: 'q7', text: '两种都喜欢', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q7-c', questionId: 'q7', text: '具体、可靠、可验证的事实', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q8: [
    { id: 'q8-a', questionId: 'q8', text: '提前完成，不喜欢最后时刻的压力', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q8-b', questionId: 'q8', text: '尽量按时，但也不过度焦虑', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q8-c', questionId: 'q8', text: '临近截止时效率更高', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
  q9: [
    { id: 'q9-a', questionId: 'q9', text: '有时会感到无聊，想找人聊天', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q9-b', questionId: 'q9', text: '适量独处很好，但不喜欢太长', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q9-c', questionId: 'q9', text: '非常必要，独处让我充电恢复', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q10: [
    { id: 'q10-a', questionId: 'q10', text: '坚持自己认为正确的立场', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q10-b', questionId: 'q10', text: '寻找平衡，兼顾各方', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q10-c', questionId: 'q10', text: '照顾所有人的感受，避免伤害', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q11: [
    { id: 'q11-a', questionId: 'q11', text: '关于未来可能发生什么的预感', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q11-b', questionId: 'q11', text: '两种都有参考价值', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q11-c', questionId: 'q11', text: '基于过去经验的现实判断', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q12: [
    { id: 'q12-a', questionId: 'q12', text: '有明确目标，按计划推进', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q12-b', questionId: 'q12', text: '方向清晰，方式灵活', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q12-c', questionId: 'q12', text: '边做边看，保持开放', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
  q13: [
    { id: 'q13-a', questionId: 'q13', text: '约上朋友，出去活动', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q13-b', questionId: 'q13', text: '视心情，两种都可以', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q13-c', questionId: 'q13', text: '一个人待着，做自己喜欢的事', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q14: [
    { id: 'q14-a', questionId: 'q14', text: '帮他们分析问题，提供解决方案', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q14-b', questionId: 'q14', text: '先共情再分析', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q14-c', questionId: 'q14', text: '认真倾听，陪伴他们感受', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q15: [
    { id: 'q15-a', questionId: 'q15', text: '充满各种可能性，还没确定方向', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q15-b', questionId: 'q15', text: '有大方向，保持弹性', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q15-c', questionId: 'q15', text: '有具体可行的步骤计划', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q16: [
    { id: 'q16-a', questionId: 'q16', text: '令人沮丧，我喜欢按计划进行', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q16-b', questionId: 'q16', text: '有点烦但能接受', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q16-c', questionId: 'q16', text: '其实挺好的，灵活才有趣', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
  q17: [
    { id: 'q17-a', questionId: 'q17', text: '很快就能打开话匣子，主动交谈', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q17-b', questionId: 'q17', text: '需要一点时间，但还好', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q17-c', questionId: 'q17', text: '比较谨慎，需要熟悉才会打开', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q18: [
    { id: 'q18-a', questionId: 'q18', text: '是否高效、有逻辑', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q18-b', questionId: 'q18', text: '效果与感受都重要', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q18-c', questionId: 'q18', text: '是否让大家都感到满意', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q19: [
    { id: 'q19-a', questionId: 'q19', text: '探索全新的领域和创意', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q19-b', questionId: 'q19', text: '创新与稳定结合', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q19-c', questionId: 'q19', text: '沿用已有的成熟方法', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q20: [
    { id: 'q20-a', questionId: 'q20', text: '不舒服，希望能有个明确答案', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q20-b', questionId: 'q20', text: '视情况而定', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q20-c', questionId: 'q20', text: '还好，开放结局更有想象空间', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
  q21: [
    { id: 'q21-a', questionId: 'q21', text: '活跃的讨论者和推动者', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q21-b', questionId: 'q21', text: '视需要调整角色', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q21-c', questionId: 'q21', text: '深度思考者和幕后贡献者', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q22: [
    { id: 'q22-a', questionId: 'q22', text: '想帮他们找到解决问题的方法', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q22-b', questionId: 'q22', text: '先安慰，再看是否需要建议', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q22-c', questionId: 'q22', text: '感同身受，想陪在他们身边', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q23: [
    { id: 'q23-a', questionId: 'q23', text: '充满隐喻与哲理的深度内容', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q23-b', questionId: 'q23', text: '两种类型都喜欢', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q23-c', questionId: 'q23', text: '有实用价值、贴近生活的内容', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q24: [
    { id: 'q24-a', questionId: 'q24', text: '尽快做决定，减少不确定感', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q24-b', questionId: 'q24', text: '根据时间压力调整', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q24-c', questionId: 'q24', text: '尽量保持开放，等有更多信息再决定', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
  q25: [
    { id: 'q25-a', questionId: 'q25', text: '更活跃，喜欢和人互动', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q25-b', questionId: 'q25', text: '视心情而定', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q25-c', questionId: 'q25', text: '更放松，享受安静', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q26: [
    { id: 'q26-a', questionId: 'q26', text: '道理是否正确，逻辑是否自洽', value: 2, dimensionScores: { 'dim-tf': 2 } },
    { id: 'q26-b', questionId: 'q26', text: '道理和关系都重要', value: 1, dimensionScores: { 'dim-tf': 0 } },
    { id: 'q26-c', questionId: 'q26', text: '双方关系是否受损', value: 0, dimensionScores: { 'dim-tf': -2 } },
  ],
  q27: [
    { id: 'q27-a', questionId: 'q27', text: '发散思维，联想各种可能', value: 2, dimensionScores: { 'dim-sn': 2 } },
    { id: 'q27-b', questionId: 'q27', text: '两种都会用', value: 1, dimensionScores: { 'dim-sn': 0 } },
    { id: 'q27-c', questionId: 'q27', text: '聚焦分析，关注具体细节', value: 0, dimensionScores: { 'dim-sn': -2 } },
  ],
  q28: [
    { id: 'q28-a', questionId: 'q28', text: '喜欢！有时最好的体验都是即兴的', value: 2, dimensionScores: { 'dim-jp': -2 } },
    { id: 'q28-b', questionId: 'q28', text: '偶尔还好，但不是常态', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q28-c', questionId: 'q28', text: '不太喜欢，更偏好有准备', value: 0, dimensionScores: { 'dim-jp': 2 } },
  ],
  q29: [
    { id: 'q29-a', questionId: 'q29', text: '感到活跃，充满能量', value: 2, dimensionScores: { 'dim-ei': 2 } },
    { id: 'q29-b', questionId: 'q29', text: '还好，视情境而定', value: 1, dimensionScores: { 'dim-ei': 0 } },
    { id: 'q29-c', questionId: 'q29', text: '有点消耗，想找个安静的角落', value: 0, dimensionScores: { 'dim-ei': -2 } },
  ],
  q30: [
    { id: 'q30-a', questionId: 'q30', text: '规则存在是有原因的，应该遵守', value: 2, dimensionScores: { 'dim-jp': 2 } },
    { id: 'q30-b', questionId: 'q30', text: '合理的规则值得遵守，不合理的可以灵活', value: 1, dimensionScores: { 'dim-jp': 0 } },
    { id: 'q30-c', questionId: 'q30', text: '规则有时会限制创造力，我倾向灵活处理', value: 0, dimensionScores: { 'dim-jp': -2 } },
  ],
};

export const mbtiResults: TestResult[] = [
  {
    id: 'res-intj',
    testId: 'test-mbti',
    typeCode: 'INTJ',
    typeName: '建筑师',
    summary: '独立、战略性的思考者，以深刻的洞察力和长远的眼光见长',
    description: '你是内心世界极为丰富的战略家。你喜欢独立思考，善于发现事物背后的规律与联系。你的目标感极强，一旦决定了方向，便会以惊人的专注和效率推进，不轻易被外界干扰。你对低效和缺乏逻辑的事情容忍度低，但对你真正在乎的领域，会投入无穷的热情与深度。',
    strengths: ['战略思维清晰', '独立自主，不依赖他人认可', '追求卓越，标准高', '善于长期规划', '逻辑分析能力强'],
    weaknesses: ['有时过于理性，忽视他人情感', '对自己和他人要求过高', '不擅长表达情感', '有时显得过于自信或固执'],
    relationships: '你在关系中重视深度而非广度。你不轻易开放自己，但一旦信任某人，会是极为忠诚的伴侣或朋友。你可能需要有意识地练习表达情感，让亲近的人感受到你真实的温度。',
    career: '适合需要战略思维和独立工作的领域：科研、工程、战略咨询、软件架构、学术研究、创业。',
    growth: '试着允许自己偶尔的不完美。练习用语言表达你内心的关怀，你不需要变得更"感性"，但让人感受到你的在乎，会让关系更圆满。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-intp',
    testId: 'test-mbti',
    typeCode: 'INTP',
    typeName: '逻辑学家',
    summary: '富有创造力的思考者，对世界充满好奇和探究欲望',
    description: '你是一个喜欢探索思想边界的人。你对几乎所有领域都充满好奇，善于发现别人没有注意到的规律和联系。你的思维跳跃而灵活，在复杂的理论世界里如鱼得水。你重视真理多于和谐，宁愿说出让人不舒服的真相，也不愿维护一个虚假的共识。',
    strengths: ['极强的分析和推理能力', '创新思维，善于发现新视角', '客观公正，不受情绪左右', '知识面广，学习能力强', '思想开放，拥抱复杂性'],
    weaknesses: ['可能忽视日常事务和实际执行', '有时过于追求理论完美而迟迟不行动', '在情感表达上较为内敛', '容易在各种想法中迷失方向'],
    relationships: '你需要一个能和你深入交流思想的伴侣。表面的寒暄对你意义不大，但当你遇到真正理解你的人，你会成为极为珍贵的存在。',
    career: '适合科学研究、软件开发、哲学、数学、数据分析、写作、系统设计等领域。',
    growth: '把你的想法付诸行动吧。一个"大概可以做"的计划，不如一个"正在做中"的行动。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-entj',
    testId: 'test-mbti',
    typeCode: 'ENTJ',
    typeName: '指挥官',
    summary: '天生的领导者，以远见和果断行动将愿景变为现实',
    description: '你是一个充满能量的行动派领导者。你善于快速识别机遇，制定清晰战略，并带领团队向目标前进。你对低效深感厌恶，总是在寻找更好的方式做事。你的自信和果断激励着周围的人，但你也需要记住——最好的计划需要人心的支持才能真正落地。',
    strengths: ['强大的领导力和执行力', '战略眼光远', '高效率，善于整合资源', '充满自信，感染力强', '勇于承担责任'],
    weaknesses: ['有时缺乏耐心', '可能忽视他人情感需求', '对"不够高效"的人缺乏包容', '工作与生活的平衡是挑战'],
    relationships: '你在关系中是主导者，你需要一个能与你并肩作战的伴侣，而不只是跟随者。学会放慢脚步，聆听身边人的感受，会让你的关系更加稳固。',
    career: '适合管理咨询、企业战略、创业、法律、政治、高管职位等需要领导力的领域。',
    growth: '最伟大的领导者不只靠智慧和效率，还靠真正理解和关怀他人。允许自己偶尔慢下来，倾听。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-entp',
    testId: 'test-mbti',
    typeCode: 'ENTP',
    typeName: '辩论家',
    summary: '充满活力的创新者，喜欢挑战常规，探索无限可能',
    description: '你的思维就像永动机——总在产生新想法，总在挑战已有的结论。你享受智识的碰撞，喜欢辩论，不是为了赢，而是为了找到更接近真相的答案。你有一种天然的魅力，能快速把握情境，用机智和幽默让对话更有活力。',
    strengths: ['创新能力强，思维活跃', '机智幽默，社交魅力强', '善于发现机遇', '适应变化，灵活性高', '能快速建立联系和关系'],
    weaknesses: ['可能三分钟热度，难以坚持到底', '争论欲强，有时显得咄咄逼人', '不喜欢细节和执行层面', '过于发散，目标不够聚焦'],
    relationships: '你需要一个能和你斗嘴、辩论，同时又不会因此受伤的伴侣。你的关系充满活力，但也需要更多的稳定性和情感连接。',
    career: '适合创业、市场营销、媒体、咨询、创意行业、产品设计等需要创新思维的领域。',
    growth: '选择一件事，坚持做完。你的想法价值无穷，但只有落地才能产生真正的影响力。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-infj',
    testId: 'test-mbti',
    typeCode: 'INFJ',
    typeName: '提倡者',
    summary: '富有洞察力的理想主义者，以深刻的共情力和远见引领变革',
    description: '你是一个内心世界极为丰富的人。你对人有着天然的洞察力，能感受到他人没有说出口的情绪。你有强烈的价值观和理想，希望世界因为自己的存在而变得更好。你既有内向的深度，又有对人类连结的渴望，这种矛盾让你独一无二。',
    strengths: ['深度共情，理解他人', '富有远见和理想', '价值观坚定', '善于洞察人心', '创造力强，有独特视角'],
    weaknesses: ['容易过度承担他人情绪', '完美主义倾向', '有时过于敏感', '难以划定健康的边界', '容易精力耗尽'],
    relationships: '你在关系中是深度的给予者。你需要的不只是陪伴，而是真正被理解。学会照顾自己，才能持续照顾他人。',
    career: '适合心理咨询、写作、教育、社会工作、艺术、人力资源、非营利组织等领域。',
    growth: '你不需要拯救所有人。先照顾好自己，你的光才能持续照亮他人。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-infp',
    testId: 'test-mbti',
    typeCode: 'INFP',
    typeName: '调停者',
    summary: '充满理想的诗人，以内心的价值观为罗盘探索生命意义',
    description: '你的内心是一个充满色彩的世界。你对人类的情感有着敏锐的感知，你的善意和同理心让周围的人感到被接纳。你有自己独特的价值观，不轻易妥协，哪怕这意味着走一条少有人走的路。你是天生的理想主义者，相信美好，也在追求美好。',
    strengths: ['深度的同理心', '创造力和想象力丰富', '对价值观的坚守', '善于倾听', '真诚，内外一致'],
    weaknesses: ['容易过于理想化', '回避冲突', '不擅长处理批评', '可能拖延决策', '容易过度内省'],
    relationships: '你渴望深度的精神连结。你是一个极为忠诚的伴侣，但也需要对方理解你偶尔需要独处的空间。',
    career: '适合写作、艺术、心理学、教育、音乐、社会工作等充满意义感的领域。',
    growth: '允许自己不完美，也允许世界不完美。行动比完美的计划更能改变现实。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-enfj',
    testId: 'test-mbti',
    typeCode: 'ENFJ',
    typeName: '主人公',
    summary: '富有感召力的领导者，天生擅长激励他人，推动集体成长',
    description: '你是一个温暖而有力量的人。你对他人的需求极为敏感，总能找到激励他人的方式。你相信每个人都有成长的潜力，并愿意用自己的能量去点燃他人的火焰。你的存在本身就是一种正能量，让团队和关系更加有活力。',
    strengths: ['强大的感召力和影响力', '善于沟通，情商高', '关心他人成长', '有责任感', '善于处理人际关系'],
    weaknesses: ['容易忽视自己的需求', '对批评过于敏感', '可能过度控制结果', '难以说"不"'],
    relationships: '你在关系中是给予者，但记得，健康的关系是双向的。允许自己也被照顾。',
    career: '适合教育、心理咨询、公共关系、非营利机构、人力资源、销售和领导岗位。',
    growth: '你的价值不仅在于你为他人做了什么，也在于你是谁。给自己一些不付出、只是存在的时间。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-enfp',
    testId: 'test-mbti',
    typeCode: 'ENFP',
    typeName: '活动家',
    summary: '充满热情的探索者，以无限的创意和感染力拥抱每一种可能',
    description: '你的生命里充满了"可能性"。你对生活充满热情，善于发现事物有趣的一面，并将这种热情传递给周围的人。你是天生的联结者，能快速与他人建立真诚的连接。你相信每个人都值得被理解，每件事都有其深层的意义。',
    strengths: ['充满创意和热情', '善于激励他人', '适应能力强', '真诚，有感染力', '对人充满好奇和善意'],
    weaknesses: ['容易分心，注意力难以持续', '可能承诺过多，执行不足', '对批评较敏感', '有时过于理想化'],
    relationships: '你在关系中充满活力和温度，但也需要一段稳定、深度的连接。找到那个能接住你热情的人。',
    career: '适合创意产业、营销、咨询、教育、心理学、公关等充满人际互动和创新的领域。',
    growth: '聚焦是你最大的挑战，也是你最大的机遇。选择你真正在乎的，然后坚持下去。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-istj',
    testId: 'test-mbti',
    typeCode: 'ISTJ',
    typeName: '物流师',
    summary: '可靠、负责任的实践者，以踏实和专注构筑稳固的生活',
    description: '你是周围人可以依赖的那个人。你有着惊人的耐力和责任感，一旦承诺就会全力履行。你重视传统和经验，相信用久经考验的方法能得到稳定的结果。你的价值不在于声张，而在于默默的坚守与付出。',
    strengths: ['极强的责任感', '踏实可靠，言出必行', '组织和执行能力强', '注重细节', '不轻易放弃'],
    weaknesses: ['有时抗拒变化', '可能过于死板', '不擅长表达情感', '有时显得过于严肃'],
    relationships: '你是一个忠诚、稳定的伴侣。你的爱体现在行动中——为对方安排好一切，解决每一个问题。',
    career: '适合会计、法律、管理、工程、军队、政府等需要严谨和责任心的领域。',
    growth: '允许自己尝试新事物。有时候，打破惯例会带来意想不到的收获。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-isfj',
    testId: 'test-mbti',
    typeCode: 'ISFJ',
    typeName: '守卫者',
    summary: '温柔细心的保护者，以无声的关爱守护身边的每一个人',
    description: '你是那种让周围人感到温暖和安全的存在。你天生善于观察他人的需求，并在不声不响中给予关怀。你重视归属感和稳定，对家人和朋友有着深深的责任感。你的付出往往默默无闻，但却是最真实的存在。',
    strengths: ['细心体贴，善解人意', '极强的责任感', '忠诚可靠', '实际能力强', '记忆力好，记得每个细节'],
    weaknesses: ['容易忽视自己的需求', '不善于拒绝', '回避冲突', '变化时容易焦虑'],
    relationships: '你用行动表达爱，细节中充满了你的用心。记得，你的需求同样值得被满足。',
    career: '适合医疗、护理、教育、行政、社会服务等以人为本的领域。',
    growth: '学会把自己放在首位。照顾好自己，才能更好地照顾他人。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-estj',
    testId: 'test-mbti',
    typeCode: 'ESTJ',
    typeName: '总经理',
    summary: '高效果断的管理者，以实际行动和清晰规则构建秩序',
    description: '你是一个天生的组织者。你相信通过明确的规则和有效的执行，任何目标都可以实现。你有强烈的责任感，不喜欢模糊和混乱。你用行动和结果说话，是团队中可以信赖的定心石。',
    strengths: ['组织能力强', '果断高效', '责任感强', '擅长执行和推动', '可靠稳定'],
    weaknesses: ['可能过于强硬', '不够灵活', '对他人情感关注不足', '有时缺乏创新性'],
    relationships: '你用行动表达对家人的爱。学习倾听和表达情感，会让你的关系更加丰富。',
    career: '适合管理、法律、金融、军队、行政等需要执行力和组织力的领域。',
    growth: '规则是工具，不是目的。偶尔允许弹性，能让你走得更远。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-esfj',
    testId: 'test-mbti',
    typeCode: 'ESFJ',
    typeName: '执政官',
    summary: '热心周到的社交者，以关怀与组织能力维系和谐的关系网络',
    description: '你天生善于照顾人。你的存在让周围的环境变得更温暖、更有序。你享受与他人的深度连接，并在帮助他人中找到价值感。你对社交关系的记忆力惊人，总能记住每个人的喜好和重要日期。',
    strengths: ['出色的社交能力', '关心他人，体贴入微', '有责任感', '善于维系关系', '组织能力好'],
    weaknesses: ['过于在意他人看法', '不善于处理冲突', '容易忽视自己', '有时过于渴望认可'],
    relationships: '你是关系中的黏合剂。但别忘了，你自己的感受也值得被关注和照顾。',
    career: '适合教育、医疗、人力资源、社区工作、活动策划等以人际关系为核心的领域。',
    growth: '你不需要所有人的认可才能知道自己是有价值的。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-istp',
    testId: 'test-mbti',
    typeCode: 'ISTP',
    typeName: '鉴赏家',
    summary: '冷静独立的实践家，以精准观察和动手能力解决一切难题',
    description: '你是一个观察者，也是一个行动者。你善于快速理解事物的运作方式，并在需要时以最高效的方式解决问题。你不依赖规则，而是依赖自己的直接经验和判断。你享受独立，不喜欢被束缚。',
    strengths: ['冷静理性，危机应对能力强', '实践能力强，心灵手巧', '独立自主', '观察力敏锐', '灵活适应'],
    weaknesses: ['不擅长表达情感', '有时显得冷漠', '对长期规划缺乏耐心', '可能有些神秘难以捉摸'],
    relationships: '你需要一个尊重你独立性的伴侣。你的爱不在言语中，而在行动里——你会默默解决所有问题。',
    career: '适合工程、机械、运动、法证、飞行员、技术员等需要实践技能的领域。',
    growth: '开口说出你的感受。你的伴侣和朋友需要的不只是你的帮助，还有你的存在感。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-isfp',
    testId: 'test-mbti',
    typeCode: 'ISFP',
    typeName: '探险家',
    summary: '温柔感性的艺术家，以开放的心感受生命中每一个细微之美',
    description: '你有一颗极为敏感的心，能感受到生活中细微的美和温度。你活在当下，不喜欢被规划束缚，享受顺其自然的生活节奏。你有强烈的个人风格，对自己的价值观有着安静的坚守，即使不会大声说出来。',
    strengths: ['艺术感和审美力强', '随和、不强加于人', '善良、有同理心', '灵活，享受当下', '真实，不做作'],
    weaknesses: ['容易回避冲突', '不善于长期规划', '对批评敏感', '可能过于被动'],
    relationships: '你用陪伴和细节表达爱。你需要一个能理解你安静，不强迫你言语表达的伴侣。',
    career: '适合艺术、设计、音乐、摄影、时尚、护理等需要感知力和创造力的领域。',
    growth: '你的感受和想法值得被听见。学会表达，不只是为了他人，也是为了自己。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-estp',
    testId: 'test-mbti',
    typeCode: 'ESTP',
    typeName: '企业家',
    summary: '精力充沛的实干家，以敏锐的洞察和行动力把握每一个机会',
    description: '你是一个活在当下的人。你有着过人的行动力和应变能力，能快速读懂场合和他人，并以机智和魅力赢得局面。你享受刺激和变化，是那种在混乱中反而最冷静的人。',
    strengths: ['反应敏捷，应变能力强', '魅力十足，善于交际', '实际，善于解决眼前问题', '精力充沛', '勇敢，不怕挑战'],
    weaknesses: ['可能缺乏长期规划', '容易冒险', '对细节和理论缺乏耐心', '可能显得过于冲动'],
    relationships: '你在关系中充满活力，但需要注意，稳定和深度同样重要。',
    career: '适合销售、创业、市场营销、急救、运动、娱乐等高能量领域。',
    growth: '慢下来，想想五年后。你的行动力是宝贵的资产，配合长远眼光，才能发挥最大价值。',
    minScore: 0,
    maxScore: 100,
  },
  {
    id: 'res-esfp',
    testId: 'test-mbti',
    typeCode: 'ESFP',
    typeName: '表演者',
    summary: '热情洋溢的表演家，把生命变成一场充满欢乐的演出',
    description: '你是天生的表演者，不是在舞台上，而是在生活里。你的热情和开朗有一种感染力，让身边的人不由自主地被你带动。你活在当下，享受每一个时刻，不想把时间浪费在担忧和计划上。',
    strengths: ['开朗热情，感染力强', '善于享受当下', '高度社交能力', '实际，行动力强', '灵活随和'],
    weaknesses: ['可能回避长期规划', '对批评敏感', '容易受情绪影响', '有时冲动行事'],
    relationships: '你的爱是热烈而真实的。你需要一个能接住你热情的伴侣，也需要偶尔沉淀下来，建立更深的连接。',
    career: '适合娱乐、活动策划、销售、服务业、教育等需要人际互动的领域。',
    growth: '你的快乐是真实的，但偶尔的沉淀，也会让你更了解自己真正想要什么。',
    minScore: 0,
    maxScore: 100,
  },
];

// ==== Big Five Test Data ====
export const bigFiveDimensions: TestDimension[] = [
  { id: 'bf-o', testId: 'test-bigfive', name: '开放性', description: '对新体验和创造力的接受程度', minLabel: '保守稳定', maxLabel: '开放创意', color: '#8b5cf6' },
  { id: 'bf-c', testId: 'test-bigfive', name: '责任心', description: '自律性和目标导向程度', minLabel: '随性灵活', maxLabel: '严谨自律', color: '#06b6d4' },
  { id: 'bf-e', testId: 'test-bigfive', name: '外向性', description: '社交能量和积极情绪水平', minLabel: '内敛安静', maxLabel: '活跃外向', color: '#10b981' },
  { id: 'bf-a', testId: 'test-bigfive', name: '宜人性', description: '对他人的合作与信任倾向', minLabel: '独立直接', maxLabel: '温和体贴', color: '#f59e0b' },
  { id: 'bf-n', testId: 'test-bigfive', name: '神经质', description: '情绪稳定性与压力应对', minLabel: '情绪稳定', maxLabel: '情绪敏感', color: '#ef4444' },
];

export const bigFiveQuestions: TestQuestion[] = [
  { id: 'bf-q1', testId: 'test-bigfive', text: '你喜欢尝试新事物和新体验', order: 1, dimensionId: 'bf-o' },
  { id: 'bf-q2', testId: 'test-bigfive', text: '你在开始工作前会做详细计划', order: 2, dimensionId: 'bf-c' },
  { id: 'bf-q3', testId: 'test-bigfive', text: '你喜欢参加聚会和社交活动', order: 3, dimensionId: 'bf-e' },
  { id: 'bf-q4', testId: 'test-bigfive', text: '你容易体谅他人的立场', order: 4, dimensionId: 'bf-a' },
  { id: 'bf-q5', testId: 'test-bigfive', text: '你容易感到担忧或紧张', order: 5, dimensionId: 'bf-n' },
  { id: 'bf-q6', testId: 'test-bigfive', text: '你喜欢思考抽象概念和理论', order: 6, dimensionId: 'bf-o' },
  { id: 'bf-q7', testId: 'test-bigfive', text: '你会按时完成任务和承诺', order: 7, dimensionId: 'bf-c' },
  { id: 'bf-q8', testId: 'test-bigfive', text: '你在与人交谈时感到充满活力', order: 8, dimensionId: 'bf-e' },
  { id: 'bf-q9', testId: 'test-bigfive', text: '你会主动帮助有困难的人', order: 9, dimensionId: 'bf-a' },
  { id: 'bf-q10', testId: 'test-bigfive', text: '你情绪波动比较明显', order: 10, dimensionId: 'bf-n' },
  { id: 'bf-q11', testId: 'test-bigfive', text: '你喜欢艺术、音乐或文学', order: 11, dimensionId: 'bf-o' },
  { id: 'bf-q12', testId: 'test-bigfive', text: '你注重做事的方式和规范', order: 12, dimensionId: 'bf-c' },
  { id: 'bf-q13', testId: 'test-bigfive', text: '你容易成为团队中的活跃分子', order: 13, dimensionId: 'bf-e' },
  { id: 'bf-q14', testId: 'test-bigfive', text: '你很少与人发生争执', order: 14, dimensionId: 'bf-a' },
  { id: 'bf-q15', testId: 'test-bigfive', text: '你有时会无缘无故地感到难过', order: 15, dimensionId: 'bf-n' },
  { id: 'bf-q16', testId: 'test-bigfive', text: '你对不同文化和思想充满好奇', order: 16, dimensionId: 'bf-o' },
  { id: 'bf-q17', testId: 'test-bigfive', text: '你会努力把每件事做到最好', order: 17, dimensionId: 'bf-c' },
  { id: 'bf-q18', testId: 'test-bigfive', text: '你在人群中感到自信和自在', order: 18, dimensionId: 'bf-e' },
  { id: 'bf-q19', testId: 'test-bigfive', text: '你相信大多数人都是善意的', order: 19, dimensionId: 'bf-a' },
  { id: 'bf-q20', testId: 'test-bigfive', text: '压力大时你容易感到不安', order: 20, dimensionId: 'bf-n' },
  { id: 'bf-q21', testId: 'test-bigfive', text: '你喜欢富有创意地解决问题', order: 21, dimensionId: 'bf-o' },
  { id: 'bf-q22', testId: 'test-bigfive', text: '你很少拖延，喜欢按时完成', order: 22, dimensionId: 'bf-c' },
  { id: 'bf-q23', testId: 'test-bigfive', text: '你喜欢主导对话和分享想法', order: 23, dimensionId: 'bf-e' },
  { id: 'bf-q24', testId: 'test-bigfive', text: '你容易受到他人情绪的影响', order: 24, dimensionId: 'bf-a' },
  { id: 'bf-q25', testId: 'test-bigfive', text: '你有时会过度担心小事', order: 25, dimensionId: 'bf-n' },
];

export const bigFiveOptionsTemplate: TestOption[] = [
  { id: 'scale-1', questionId: '', text: '完全不符合', value: 1, dimensionScores: {} },
  { id: 'scale-2', questionId: '', text: '比较不符合', value: 2, dimensionScores: {} },
  { id: 'scale-3', questionId: '', text: '不确定', value: 3, dimensionScores: {} },
  { id: 'scale-4', questionId: '', text: '比较符合', value: 4, dimensionScores: {} },
  { id: 'scale-5', questionId: '', text: '完全符合', value: 5, dimensionScores: {} },
];

// ==== Career Tendency Test Data ====
export const careerDimensions: TestDimension[] = [
  { id: 'car-r', testId: 'test-career', name: '实践型', description: '动手操作和技术能力', minLabel: '低', maxLabel: '高', color: '#f59e0b' },
  { id: 'car-i', testId: 'test-career', name: '研究型', description: '分析思考和学术倾向', minLabel: '低', maxLabel: '高', color: '#8b5cf6' },
  { id: 'car-a', testId: 'test-career', name: '艺术型', description: '创造力和美学表达', minLabel: '低', maxLabel: '高', color: '#ec4899' },
  { id: 'car-s', testId: 'test-career', name: '社会型', description: '帮助他人和人际互动', minLabel: '低', maxLabel: '高', color: '#10b981' },
  { id: 'car-e', testId: 'test-career', name: '管理型', description: '领导力和商业能力', minLabel: '低', maxLabel: '高', color: '#06b6d4' },
  { id: 'car-c', testId: 'test-career', name: '事务型', description: '细节处理和规范执行', minLabel: '低', maxLabel: '高', color: '#64748b' },
];

// Helper to get test questions and options
export function getTestData(testId: string) {
  switch (testId) {
    case 'test-mbti':
      return {
        test: tests.find(t => t.id === testId),
        dimensions: mbtiDimensions,
        questions: mbtiQuestions,
        options: mbtiOptions,
        results: mbtiResults,
      };
    case 'test-bigfive':
      return {
        test: tests.find(t => t.id === testId),
        dimensions: bigFiveDimensions,
        questions: bigFiveQuestions,
        options: {},
        results: [],
      };
    default:
      return {
        test: tests.find(t => t.id === testId),
        dimensions: [],
        questions: [],
        options: {},
        results: [],
      };
  }
}

export function calculateMbtiResult(answers: Record<string, string>): {
  typeCode: string;
  dimensionScores: Record<string, number>;
  result: TestResult;
} {
  const dimScores: Record<string, number> = {
    'dim-ei': 0,
    'dim-sn': 0,
    'dim-tf': 0,
    'dim-jp': 0,
  };

  mbtiQuestions.forEach((q) => {
    const answeredOptionId = answers[q.id];
    if (!answeredOptionId) return;
    const opts = mbtiOptions[q.id];
    if (!opts) return;
    const opt = opts.find(o => o.id === String(answeredOptionId));
    if (!opt) return;
    Object.entries(opt.dimensionScores).forEach(([dim, score]) => {
      dimScores[dim] = (dimScores[dim] || 0) + score;
    });
  });

  const e = dimScores['dim-ei'] > 0 ? 'E' : 'I';
  const n = dimScores['dim-sn'] > 0 ? 'N' : 'S';
  const t = dimScores['dim-tf'] > 0 ? 'T' : 'F';
  const j = dimScores['dim-jp'] > 0 ? 'J' : 'P';
  const typeCode = `${e}${n}${t}${j}`;

  const result = mbtiResults.find(r => r.typeCode === typeCode) || mbtiResults[0];
  return { typeCode, dimensionScores: dimScores, result };
}


// ==== SBTI 人格测试 ====
// Silly Big Personality Test —— 2026年4月爆火的娱乐向人格测试
// 机制：31道题，每题A/B/C，选项对应27种人格类型得分，最终取最高分对应类型

export const sbtiQuestions = [
  {
    id: 'sb-q1', testId: 'test-sbti', order: 1,
    text: '一个萌萌的小女孩向你走来，递给你一颗棒棒糖，你第一反应是…',
    options: [
      { id: 'sb-q1-a', text: '哇好可爱，接过来谢谢她😊', scores: { HHHH: 3, MUM: 2, LOVR: 1 } },
      { id: 'sb-q1-b', text: '这孩子是来干嘛的，会不会有什么企图', scores: { SHIT: 2, IMSB: 1, THIN: 2 } },
      { id: 'sb-q1-c', text: '（内心一片空白，接过来，保持微笑）', scores: { FAKE: 3, ZZZZ: 2, OJBK: 1 } },
    ],
  },
  {
    id: 'sb-q2', testId: 'test-sbti', order: 2,
    text: '今天计划休息一天，但朋友突然叫你出去玩，你会…',
    options: [
      { id: 'sb-q2-a', text: '立刻换装出门，生命在于运动！', scores: { GOGO: 3, CTRL: 1, BOSS: 1 } },
      { id: 'sb-q2-b', text: '找借口说身体不舒服，继续躺着', scores: { ZZZZ: 3, MALO: 2, DEAD: 1 } },
      { id: 'sb-q2-c', text: '"好啊"（内心：我的休息日…）', scores: { FAKE: 2, MUM: 2, SOLO: 1 } },
    ],
  },
  {
    id: 'sb-q3', testId: 'test-sbti', order: 3,
    text: '在饭桌上，亲戚问你"工资多少"，你会…',
    options: [
      { id: 'sb-q3-a', text: '直接报数字，有什么不好说的', scores: { BOSS: 2, CTRL: 1, GOGO: 1 } },
      { id: 'sb-q3-b', text: '"还行吧"然后低头扒饭', scores: { SOLO: 2, MALO: 2, OJBK: 1 } },
      { id: 'sb-q3-c', text: '（在心里说了很多脏话）"不多不多"', scores: { FUCK: 3, SHIT: 2, IMSB: 1 } },
    ],
  },
  {
    id: 'sb-q4', testId: 'test-sbti', order: 4,
    text: '你被便秘困在马桶上30分钟了，你会…',
    options: [
      { id: 'sb-q4-a', text: '刷手机，当厕所是第二个家', scores: { EAT: 2, HHHH: 2, MALO: 2 } },
      { id: 'sb-q4-b', text: '陷入存在主义危机，开始思考人生', scores: { THIN: 3, MONK: 2, IMSB: 1 } },
      { id: 'sb-q4-c', text: '（内心狂骂，表情平静）坐着等', scores: { ZZZZ: 3, OJBK: 2, FUCK: 1 } },
    ],
  },
  {
    id: 'sb-q5', testId: 'test-sbti', order: 5,
    text: '发现同事在背后说自己坏话，你会…',
    options: [
      { id: 'sb-q5-a', text: '直接找他对质，今天必须说清楚', scores: { BOSS: 3, CTRL: 2, FUCK: 2 } },
      { id: 'sb-q5-b', text: '假装不知道，继续表面和平', scores: { FAKE: 3, OJBK: 2, ZZZZ: 1 } },
      { id: 'sb-q5-c', text: '独自消化，又开始反省是不是自己的问题', scores: { IMSB: 3, THIN: 2, SOLO: 2 } },
    ],
  },
  {
    id: 'sb-q6', testId: 'test-sbti', order: 6,
    text: '朋友突然哭着给你发消息说失恋了，你会…',
    options: [
      { id: 'sb-q6-a', text: '立刻打电话，全程陪伴安慰', scores: { MUM: 3, LOVR: 3, THANK: 1 } },
      { id: 'sb-q6-b', text: '发个拥抱表情，等她说完再回', scores: { OJBK: 2, FAKE: 1, HHHH: 1 } },
      { id: 'sb-q6-c', text: '"又失恋了？"然后开始提建议', scores: { CTRL: 2, BOSS: 2, THIN: 1 } },
    ],
  },
  {
    id: 'sb-q7', testId: 'test-sbti', order: 7,
    text: '一觉醒来发现今天不需要上班，你的第一反应是…',
    options: [
      { id: 'sb-q7-a', text: '！！！立刻开始规划今天怎么玩', scores: { GOGO: 3, HHHH: 2, EAT: 2 } },
      { id: 'sb-q7-b', text: '继续睡，睡到自然醒再说', scores: { DEAD: 3, ZZZZ: 3, MALO: 2 } },
      { id: 'sb-q7-c', text: '焦虑——有什么事情还没做完吗', scores: { IMSB: 2, CTRL: 2, THIN: 2 } },
    ],
  },
  {
    id: 'sb-q8', testId: 'test-sbti', order: 8,
    text: '有人突然问你借钱，你会…',
    options: [
      { id: 'sb-q8-a', text: '借！朋友有难怎么能不帮', scores: { ATM: 3, MUM: 2, LOVR: 1 } },
      { id: 'sb-q8-b', text: '"最近手头也紧"（其实没有）', scores: { POOR: 2, SOLO: 2, FAKE: 2 } },
      { id: 'sb-q8-c', text: '看情况，问清楚原因再决定', scores: { CTRL: 2, BOSS: 2, THIN: 1 } },
    ],
  },
  {
    id: 'sb-q9', testId: 'test-sbti', order: 9,
    text: '下面这句话，哪个最像你对朋友说的…',
    options: [
      { id: 'sb-q9-a', text: '"你这样做不对，应该这样……"（说了很久）', scores: { BOSS: 2, CTRL: 3, MUM: 1 } },
      { id: 'sb-q9-b', text: '"你开心就好"（然后继续摸鱼）', scores: { MALO: 3, OJBK: 3, DEAD: 1 } },
      { id: 'sb-q9-c', text: '"你好可怜哦"（内心也在哭）', scores: { LOVR: 2, THANK: 2, IMSB: 2 } },
    ],
  },
  {
    id: 'sb-q10', testId: 'test-sbti', order: 10,
    text: '你看见路边有人摔倒了，你会…',
    options: [
      { id: 'sb-q10-a', text: '立刻跑过去扶，询问是否需要帮助', scores: { MUM: 3, GOGO: 1, THANK: 2 } },
      { id: 'sb-q10-b', text: '停了一下，观察一下，再过去', scores: { THIN: 2, CTRL: 1, FAKE: 1 } },
      { id: 'sb-q10-c', text: '（哦不）拿出手机……', scores: { WOC: 3, HHHH: 1, OJBK: 2 } },
    ],
  },
  {
    id: 'sb-q11', testId: 'test-sbti', order: 11,
    text: '参加一个全是陌生人的聚会，你会…',
    options: [
      { id: 'sb-q11-a', text: '全场认识一遍，笑容挂全程', scores: { SEXY: 3, BOSS: 2, GOGO: 1 } },
      { id: 'sb-q11-b', text: '找个角落，看手机或假装喝饮料', scores: { SOLO: 3, DEAD: 2, ZZZZ: 1 } },
      { id: 'sb-q11-c', text: '表面活跃，内心如木', scores: { FAKE: 3, JOKR: 2, IMSB: 1 } },
    ],
  },
  {
    id: 'sb-q12', testId: 'test-sbti', order: 12,
    text: '你最近最大的烦恼是…',
    options: [
      { id: 'sb-q12-a', text: '没钱', scores: { POOR: 4, ATM: 2, MALO: 1 } },
      { id: 'sb-q12-b', text: '没意思，对什么都提不起劲', scores: { DEAD: 4, MONK: 2, ZZZZ: 1 } },
      { id: 'sb-q12-c', text: '想太多，脑子停不下来', scores: { THIN: 4, IMSB: 2, JOKR: 1 } },
    ],
  },
  {
    id: 'sb-q13', testId: 'test-sbti', order: 13,
    text: '和别人争论时，你通常是…',
    options: [
      { id: 'sb-q13-a', text: '我必须说清楚，不然难受', scores: { BOSS: 3, CTRL: 2, FUCK: 2 } },
      { id: 'sb-q13-b', text: '"随便"（然后在心里继续骂）', scores: { FUCK: 3, IMSB: 2, OJBK: 1 } },
      { id: 'sb-q13-c', text: '逃离现场或沉默', scores: { SOLO: 3, DEAD: 2, MONK: 2 } },
    ],
  },
  {
    id: 'sb-q14', testId: 'test-sbti', order: 14,
    text: '（没有问题）',
    options: [
      { id: 'sb-q14-a', text: 'A', scores: { LUCK: 3, HHHH: 1, OJBK: 1 } },
      { id: 'sb-q14-b', text: 'B', scores: { THIN: 2, IMSB: 2, MONK: 1 } },
      { id: 'sb-q14-c', text: 'C', scores: { WOC: 3, FUCK: 1, DEAD: 1 } },
    ],
  },
  {
    id: 'sb-q15', testId: 'test-sbti', order: 15,
    text: '你最常用来解压的方式是…',
    options: [
      { id: 'sb-q15-a', text: '吃！吃完什么都好了', scores: { EAT: 4, HHHH: 2, POOR: 1 } },
      { id: 'sb-q15-b', text: '睡觉，睡到忘记烦恼', scores: { ZZZZ: 4, DEAD: 2, MALO: 2 } },
      { id: 'sb-q15-c', text: '喝酒，微醺的时候最自由', scores: { DRNK: 4, JOKR: 1, LOVR: 1 } },
    ],
  },
  {
    id: 'sb-q16', testId: 'test-sbti', order: 16,
    text: '别人说"你变了"，你的反应是…',
    options: [
      { id: 'sb-q16-a', text: '是吗？变好了还是变坏了？（认真分析）', scores: { THIN: 3, CTRL: 1, BOSS: 1 } },
      { id: 'sb-q16-b', text: '我从来没有变过，本来就这样', scores: { MONK: 2, OJBK: 2, SEXY: 1 } },
      { id: 'sb-q16-c', text: '（我本来是什么样的？越想越迷茫）', scores: { FAKE: 3, IMSB: 2, THIN: 1 } },
    ],
  },
  {
    id: 'sb-q17', testId: 'test-sbti', order: 17,
    text: '你对"内卷"这件事的态度是…',
    options: [
      { id: 'sb-q17-a', text: '卷！不卷怎么能赢', scores: { BOSS: 2, GOGO: 3, CTRL: 1 } },
      { id: 'sb-q17-b', text: '躺平！卷有什么意思', scores: { MALO: 4, DEAD: 2, ZZZZ: 1 } },
      { id: 'sb-q17-c', text: '（想卷，但卷不动）', scores: { IMSB: 3, POOR: 1, SHIT: 2 } },
    ],
  },
  {
    id: 'sb-q18', testId: 'test-sbti', order: 18,
    text: '你最近一次哭，是因为…',
    options: [
      { id: 'sb-q18-a', text: '被人说了两句好话，绷不住了', scores: { THANK: 4, LOVR: 2, IMSB: 1 } },
      { id: 'sb-q18-b', text: '想到了某件很久以前的事', scores: { THIN: 3, LOVR: 2, SOLO: 1 } },
      { id: 'sb-q18-c', text: '我不哭，忘了上次哭是什么时候了', scores: { DEAD: 3, MONK: 2, SHIT: 2 } },
    ],
  },
  {
    id: 'sb-q19', testId: 'test-sbti', order: 19,
    text: '你对"他人的评价"的态度是…',
    options: [
      { id: 'sb-q19-a', text: '无所谓，你们随便说', scores: { OJBK: 3, MONK: 2, MALO: 1 } },
      { id: 'sb-q19-b', text: '（表面无所谓，实际记了一百年）', scores: { FAKE: 2, IMSB: 3, THANK: 1 } },
      { id: 'sb-q19-c', text: '挺在意的，我承认', scores: { LOVR: 2, CTRL: 1, IMSB: 2 } },
    ],
  },
  {
    id: 'sb-q20', testId: 'test-sbti', order: 20,
    text: '如果可以拥有一种超能力，你会选…',
    options: [
      { id: 'sb-q20-a', text: '瞬间移动，随时逃离任何场合', scores: { SOLO: 3, DEAD: 1, ZZZZ: 1 } },
      { id: 'sb-q20-b', text: '读心术，知道别人在想什么', scores: { CTRL: 3, THIN: 2, BOSS: 1 } },
      { id: 'sb-q20-c', text: '永远不需要钱，花不完', scores: { POOR: 4, ATM: 1, HHHH: 2 } },
    ],
  },
  {
    id: 'sb-q21', testId: 'test-sbti', order: 21,
    text: '你最不想听到的一句话是…',
    options: [
      { id: 'sb-q21-a', text: '"你能不能振作一点"', scores: { DEAD: 3, MALO: 2, ZZZZ: 1 } },
      { id: 'sb-q21-b', text: '"我需要跟你认真谈谈"', scores: { WOC: 3, IMSB: 2, THIN: 1 } },
      { id: 'sb-q21-c', text: '"下次你来请客"', scores: { POOR: 4, ATM: 2, FUCK: 1 } },
    ],
  },
  {
    id: 'sb-q22', testId: 'test-sbti', order: 22,
    text: '深夜3点，你在干嘛…',
    options: [
      { id: 'sb-q22-a', text: '睡觉，我作息规律', scores: { MONK: 3, CTRL: 2, BOSS: 1 } },
      { id: 'sb-q22-b', text: '刷手机或看剧，根本睡不着', scores: { THIN: 2, DRNK: 1, MALO: 2 } },
      { id: 'sb-q22-c', text: '喝酒或瞎想人生', scores: { DRNK: 4, SHIT: 2, JOKR: 1 } },
    ],
  },
  {
    id: 'sb-q23', testId: 'test-sbti', order: 23,
    text: '有人突然夸你"你今天好漂亮/帅"，你会…',
    options: [
      { id: 'sb-q23-a', text: '谢谢！我知道的😏', scores: { SEXY: 4, BOSS: 1, HHHH: 1 } },
      { id: 'sb-q23-b', text: '（内心雀跃，表面镇定）"没有啦"', scores: { THANK: 3, FAKE: 2, LOVR: 1 } },
      { id: 'sb-q23-c', text: '他在讽刺我吗……', scores: { IMSB: 3, SHIT: 2, THIN: 1 } },
    ],
  },
  {
    id: 'sb-q24', testId: 'test-sbti', order: 24,
    text: '你最常对自己说的话是…',
    options: [
      { id: 'sb-q24-a', text: '"算了，反正也无所谓"', scores: { OJBK: 4, MALO: 2, DEAD: 1 } },
      { id: 'sb-q24-b', text: '"怎么又是我的问题"', scores: { IMSB: 4, SHIT: 1, THIN: 1 } },
      { id: 'sb-q24-c', text: '"我行的，再撑一下"', scores: { GOGO: 3, BOSS: 2, THANK: 1 } },
    ],
  },
  {
    id: 'sb-q25', testId: 'test-sbti', order: 25,
    text: '有一天你意外得到了一笔钱，你会…',
    options: [
      { id: 'sb-q25-a', text: '立刻去吃最贵的那家餐厅！', scores: { EAT: 4, HHHH: 2, GOGO: 1 } },
      { id: 'sb-q25-b', text: '存起来，以后用', scores: { CTRL: 2, BOSS: 1, THIN: 2 } },
      { id: 'sb-q25-c', text: '借给朋友……（然后要不回来）', scores: { ATM: 4, MUM: 2, POOR: 1 } },
    ],
  },
  {
    id: 'sb-q26', testId: 'test-sbti', order: 26,
    text: '你觉得自己最大的问题是…',
    options: [
      { id: 'sb-q26-a', text: '太懒，什么都不想动', scores: { MALO: 3, DEAD: 3, ZZZZ: 2 } },
      { id: 'sb-q26-b', text: '太软，总是帮别人吃亏', scores: { ATM: 3, MUM: 2, THANK: 1 } },
      { id: 'sb-q26-c', text: '太作，喜欢自己折腾自己', scores: { IMSB: 4, THIN: 2, WOC: 1 } },
    ],
  },
  {
    id: 'sb-q27', testId: 'test-sbti', order: 27,
    text: '你的朋友圈/社交媒体通常发…',
    options: [
      { id: 'sb-q27-a', text: '美食、日常、快乐碎片', scores: { EAT: 2, HHHH: 3, GOGO: 1 } },
      { id: 'sb-q27-b', text: '很少发，发了也很快删掉', scores: { SOLO: 3, FAKE: 2, IMSB: 1 } },
      { id: 'sb-q27-c', text: '深夜感悟或让人看不懂的句子', scores: { JOKR: 2, THIN: 3, DRNK: 1 } },
    ],
  },
  {
    id: 'sb-q28', testId: 'test-sbti', order: 28,
    text: '你觉得"幸运"这件事…',
    options: [
      { id: 'sb-q28-a', text: '跟我无关，倒霉的总是我', scores: { SHIT: 3, OHNO: 4, POOR: 1 } },
      { id: 'sb-q28-b', text: '时好时坏，看心情', scores: { LUCK: 4, OJBK: 2, HHHH: 1 } },
      { id: 'sb-q28-c', text: '我总体还是比较走运的', scores: { LUCK: 2, SEXY: 2, BOSS: 1 } },
    ],
  },
  {
    id: 'sb-q29', testId: 'test-sbti', order: 29,
    text: '下班路上你在想…',
    options: [
      { id: 'sb-q29-a', text: '今天吃什么！！！', scores: { EAT: 4, HHHH: 2, GOGO: 1 } },
      { id: 'sb-q29-b', text: '今天哪里出了错，明天还能改吗', scores: { IMSB: 3, THIN: 3, CTRL: 1 } },
      { id: 'sb-q29-c', text: '什么都没想，已经进入省电模式', scores: { DEAD: 3, MALO: 2, ZZZZ: 2 } },
    ],
  },
  {
    id: 'sb-q30', testId: 'test-sbti', order: 30,
    text: '别人跟你说"我最近很累"，你的回复是…',
    options: [
      { id: 'sb-q30-a', text: '"我也是！我们一起累吧"', scores: { JOKR: 3, HHHH: 2, MALO: 1 } },
      { id: 'sb-q30-b', text: '"要不要聊聊？我陪着你"', scores: { MUM: 3, LOVR: 2, THANK: 2 } },
      { id: 'sb-q30-c', text: '"嗯"（因为我也没力气安慰人了）', scores: { DEAD: 3, OJBK: 2, ZZZZ: 1 } },
    ],
  },
  {
    id: 'sb-q31', testId: 'test-sbti', order: 31,
    text: '最后一道题：你现在感觉怎么样？',
    options: [
      { id: 'sb-q31-a', text: '还好，正常活着', scores: { MALO: 2, OJBK: 2, HHHH: 2 } },
      { id: 'sb-q31-b', text: '累，但撑着', scores: { GOGO: 2, IMSB: 2, THANK: 2 } },
      { id: 'sb-q31-c', text: '不知道，空白状态', scores: { DEAD: 3, MONK: 2, THIN: 1 } },
    ],
  },
];

export const sbtiResults = [
  {
    id: 'sb-malo', testId: 'test-sbti', typeCode: 'MALO',
    typeName: '吗喽',
    summary: '佛系打工人，拒绝内卷，只想安稳摸鱼',
    description: '你是当代社会的清醒旁观者。"吗喽"本是对打工人的自嘲，你深知内卷的荒诞，选择以低耗能的方式应对高压世界。你不是真的懒——只是懒得演。你的智慧在于：知道什么事值得努力，什么事不值得。',
    strengths: ['心态稳健，不轻易焦虑', '不争不抢，内心自有标准', '善于保留能量给真正重要的事'],
    weaknesses: ['有时会错失机会', '容易被误认为不上进', '偶尔会后悔当时没拼一把'],
    relationships: '你在关系里不爱主动，但一旦开始就很稳定。你不喜欢戏精，欣赏同样懂得"差不多就行"的人。',
    career: '适合节奏稳定、不靠"激情"驱动的工作。你能把普通的岗位做得扎实，是靠谱的执行者。',
    growth: '偶尔允许自己认真一次——不是为了赢，而是看看自己到底能走多远。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-dead', testId: 'test-sbti', typeCode: 'DEAD',
    typeName: '死者',
    summary: '心已躺平，无欲无求，对啥都没兴趣',
    description: '你抵达了一种极致的"平静"——不是冥想出来的，而是被生活耗尽之后的副产品。你并非真的不在乎，只是在乎过太多次、失望过太多次，最后选择了"情感节能模式"。你是深藏功与名的人。',
    strengths: ['超强抗压能力，已无可击败', '不会被情绪绑架', '内心其实有很深的感受，只是不说'],
    weaknesses: ['很难被激励起来', '可能错过真正有意义的连结', '对自己和他人的期望都很低'],
    relationships: '很少主动，但若有人真的走进来，你会比谁都真诚。你需要一个不逼你"振作"的伴侣。',
    career: '最适合稳定的、不需要热情驱动的工作。你的优势是：不会因情绪波动影响输出质量。',
    growth: '找一件让你愿意"多看一眼"的事。不用是热情，只要有一点点好奇就够了。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-zzzz', testId: 'test-sbti', typeCode: 'ZZZZ',
    typeName: '装死者',
    summary: '表面摆烂，用睡觉逃避，遇事就装死',
    description: '你是人类进化的最新成果：在任何困难面前，你都能以惊人的速度进入"系统休眠"状态。睡觉是你的盾牌，摆烂是你的武器，但你其实比任何人都清楚问题在哪里——只是暂时选择不面对。',
    strengths: ['极强的自我保护能力', '知道何时该"关机"修复', '清醒时效率其实不低'],
    weaknesses: ['拖延症晚期', '重要的事总被睡眠打断', '清醒后会有一波强烈的罪恶感'],
    relationships: '感情里很被动，但睡醒了真的很好。你需要一个懂得让你"充电"的人，而不是不停催你起床的人。',
    career: '灵活时间或项目制工作很适合你。集中爆发的能量，加上充分的休息，你能产出不错的结果。',
    growth: '下次遇到难题，先睡一觉没问题——但记得醒来之后给自己一个小时，真的去面对它。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-fake', testId: 'test-sbti', typeCode: 'FAKE',
    typeName: '伪人',
    summary: '社交面具人，人前一套人后一套，活很累',
    description: '你在社交场合永远表现良好，但那个"你"和真实的你之间隔着一面镜子。你不是坏人——你只是太懂得如何适应每一个场合，久而久之连自己都分不清哪个才是本体。累，但停不下来。',
    strengths: ['极强的社交适应能力', '善于照顾他人感受', '在任何场合都能圆场'],
    weaknesses: ['自我认知模糊', '内心疲惫', '偶尔想要"做自己"却不知道自己是谁'],
    relationships: '你善于维系表面和谐，但真正的亲密关系需要你拿掉面具。找那个让你可以"休息"的人。',
    career: '销售、公关、服务业……所有需要"得体"的场合，你都如鱼得水。但内心需要有一个属于自己的出口。',
    growth: '每天给自己留10分钟，做一件完全不用表演的事。哪怕只是一个人发发呆。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-imsb', testId: 'test-sbti', typeCode: 'IMSB',
    typeName: '自我攻击者',
    summary: '总怪自己，爱内耗，一边努力一边否定',
    description: '你是自己最苛刻的批评者。任何事情出了差错，第一个怀疑的总是自己；别人一个眼神，你能解读出一篇论文。你很努力，但那份努力里有一半是在和自己的声音博弈。',
    strengths: ['高度自省，不断成长', '做事认真细致', '有强烈的责任感'],
    weaknesses: ['内耗严重', '容易陷入自我怀疑的死循环', '对自己的要求远高于他人'],
    relationships: '你爱得很深，但也需要对方不断确认你的价值。找一个懂得及时给你反馈的人。',
    career: '适合需要精益求精的工作。但记得设定"够好了"的边界，不然你会把自己耗空。',
    growth: '今天试着对一件做得还可以的事说："这已经够好了。"',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-boss', testId: 'test-sbti', typeCode: 'BOSS',
    typeName: '领导者',
    summary: '气场强，爱掌控，天生带队、爱决策',
    description: '你走进一个房间，空气会感受到你。你有天然的决策欲和号召力，习惯站在局面的中心，把事情推进。你不是非要出风头，只是你的大脑就是为"解决问题、推动结果"而运转的。',
    strengths: ['执行力强，说到做到', '善于把控全局', '在混乱中能迅速找到方向'],
    weaknesses: ['有时控制欲过强', '不善于让别人慢下来', '对"不效率"的人缺乏耐心'],
    relationships: '你在关系里会自然承担更多，但也要允许对方有自己的节奏。真正的连结不是管理，是理解。',
    career: '管理、创业、项目负责、团队带领……有决策权的位置都是你的主场。',
    growth: '学会把一件事的控制权完全交出去，然后观察别人如何处理——你会发现新的角度。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-mum', testId: 'test-sbti', typeCode: 'MUM',
    typeName: '妈妈型',
    summary: '爱操心、会照顾人，温柔包容、总付出',
    description: '你是朋友圈里的"妈妈"。不论你实际年龄多大，你总是那个准备好纸巾、记得所有人饮食禁忌、第一个发现有人不对劲的人。你的爱是实质性的，体现在每一个细节的照顾里。',
    strengths: ['高度共情，善于照顾他人', '记忆细节能力超强', '让身边人感到安全'],
    weaknesses: ['习惯把他人需求放在自己之前', '很难开口说"我也需要帮助"', '容易被消耗'],
    relationships: '你是最好的伴侣候选人之一，但你也需要一个会反过来照顾你的人。',
    career: '教育、医护、社工、咨询……所有需要真心照料他人的领域，你都能做得出色。',
    growth: '今天做一件只为自己的事，不要带任何"有没有帮到别人"的考量。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-ctrl', testId: 'test-sbti', typeCode: 'CTRL',
    typeName: '拿捏者',
    summary: '控制欲强，擅长拿捏，凡事要自己掌控',
    description: '你是行走的任务管理器。你的大脑随时在运行多个进程：跟踪当前状态、预判下一步、排查风险。你不是不信任别人，只是"交给别人"这件事对你来说本身就是一种压力。',
    strengths: ['极强的计划和组织能力', '对细节敏感，不容易出错', '稳定可靠，是团队的安全感来源'],
    weaknesses: ['难以放权', '在不确定中会焦虑', '对"失控感"极度不适'],
    relationships: '你善于把关系打理得井井有条，但感情不是项目，允许一些"不确定"发生。',
    career: '项目管理、运营、财务、质控……所有需要严谨掌控的岗位都是你的位置。',
    growth: '今天故意做一件没有计划的事，看看会发生什么——大概率没有你想的那么糟。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-fuck', testId: 'test-sbti', typeCode: 'FUCK',
    typeName: '草者',
    summary: '嘴硬暴躁爱吐槽，内心却默默扛事',
    description: '你说话直，脾气冲，嘴上永远是"草""日""算了我去"，但真遇到事，你是第一个默默冲上去的人。你的暴躁是面具，里面包的是一颗比谁都认真的心。',
    strengths: ['真实，不装', '关键时刻冲得上', '吐槽准确，直击本质'],
    weaknesses: ['第一反应容易吓到别人', '语气让人感到被攻击', '事后会后悔说太重了'],
    relationships: '你爱得粗糙但真实。找一个不怕你"嘴臭"、知道你在乎的人。',
    career: '任何需要直接反馈的岗位都很适合你。设计、评审、运营……你的"嘴毒"是一种才能。',
    growth: '下次在吐槽之前，先深呼吸一口——不是为了憋回去，而是让那句话落地更稳。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-shit', testId: 'test-sbti', typeCode: 'SHIT',
    typeName: '狗屎人',
    summary: '愤世嫉俗，觉得世界很烂，却仍认真生活',
    description: '你对世界保持着清醒的悲观，但你没有因此躺下——你选择了带着"这一切都是坨屎"的认知继续认真活着。这反而是一种罕见的清醒：你不需要幻觉来支撑自己前行。',
    strengths: ['对现实有清醒认知', '不被虚假的乐观所迷惑', '在逆境中也能维持行动'],
    weaknesses: ['容易陷入愤世嫉俗的低落', '很难和"积极人"相处', '偶尔会把自己的悲观传染给周围人'],
    relationships: '你需要一个同样清醒、但不会一起往下坠的人。能和你一起吐槽，也能在你最低落时拉你一把的人。',
    career: '媒体、评论、产品测试……所有需要"挑毛病"能力的领域，你是天才。',
    growth: '找一件你认为"这个是真的好"的事。不管多小，写下来。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-solo', testId: 'test-sbti', typeCode: 'SOLO',
    typeName: '孤儿',
    summary: '习惯独处，不爱麻烦人，也不想被麻烦',
    description: '你高度自给自足。你不是孤独，你只是非常擅长独处。你解决自己的问题，消化自己的情绪，偶尔也会羡慕那种"随时有人在"的生活，但一旦真的有人靠太近，你又会感到窒息。',
    strengths: ['高度自律和独立', '不依赖他人，内心稳定', '独处时高效且有创造力'],
    weaknesses: ['有时孤立感很强', '不擅长主动求助', '关系维系上容易断线'],
    relationships: '你需要的不是黏人的伴侣，而是那种"即使不说话也能陪着你"的存在感。',
    career: '远程工作、独立研究、写作、技术……给你空间，你能做出最好的东西。',
    growth: '今天主动联系一个许久没联系的人，哪怕只说一句"你最近怎样"。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-ojbk', testId: 'test-sbti', typeCode: 'OJBK',
    typeName: '无所谓人',
    summary: '怎么都行，没主见，佛系到近乎冷漠',
    description: '"去哪都行""吃什么都可""你决定吧"——你是人类世界里最不挑剔的存在。你不是没有想法，只是觉得表达出来要耗费太多能量，而且结果往往也不差。这是一种超级省力的生存哲学。',
    strengths: ['适应性极强', '很少和人产生冲突', '内心平静稳定'],
    weaknesses: ['关键时刻缺乏立场', '容易被别人的决定牵着走', '有时会后悔没坚持自己的想法'],
    relationships: '你是最好相处的伴侣之一，但偶尔表达一下你的偏好——对方其实很想知道。',
    career: '配合型、支持型的岗位很适合你。你是团队里的润滑剂。',
    growth: '下次有人问你"去哪吃"，说出你真正想去的那个地方。就这一次。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-jokr', testId: 'test-sbti', typeCode: 'JOKR',
    typeName: '小丑',
    summary: '用搞笑掩饰孤独，热闹里最孤单',
    description: '你是聚会的灵魂，段子库最丰富的那个，总能活跃气氛。但当所有人都笑了，有时候你会感觉自己是最孤单的人。你用幽默把自己和他人之间的距离维持得恰到好处——既够近，又不太近。',
    strengths: ['天才的幽默感', '让身边人感到轻松', '化解尴尬的高手'],
    weaknesses: ['很少被认真对待', '自己受伤时很难开口', '有时用笑声掩盖了真实需求'],
    relationships: '你需要一个愿意在大家都笑的时候，注意到你眼角那点点不一样的人。',
    career: '内容创作、喜剧、主持、社群运营……你的幽默是真正的才能。',
    growth: '和你最信任的人说一次不是玩笑的话——哪怕很短，哪怕很普通。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-sexy', testId: 'test-sbti', typeCode: 'SEXY',
    typeName: '尤物',
    summary: '自带魅力气场，自信亮眼，人群吸睛',
    description: '你走进一个房间，整个房间的空气都会微微流动。你不需要努力"表现"，你的存在本身就有磁场。你对自己很清楚，知道自己的价值，不需要他人的认可来完整自己。',
    strengths: ['高度自信，气场强大', '人际吸引力强', '内心稳定，不轻易被动摇'],
    weaknesses: ['有时被误解为傲慢', '容易让他人产生压力', '对不如自己的人有时缺乏耐心'],
    relationships: '你需要一个能够"配得上"你的人——不是地位上的，而是内心同样稳定的人。',
    career: '任何有展示性的工作都适合你：销售、媒体、公关、表演……你是天生的前台人。',
    growth: '允许自己偶尔不那么"在状态"，脆弱也是真实的一部分。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-gogo', testId: 'test-sbti', typeCode: 'GOGO',
    typeName: '行者',
    summary: '永动机行动派，闲不住，一生奔波劳碌',
    description: '你是人类当中的永动机。你的默认状态是"动着"，停下来反而让你焦虑。你不一定知道终点在哪里，但你就是停不下来。有时候你羡慕那些能闲着的人，但只要5分钟，你就会开始想"再去做点什么"。',
    strengths: ['行动力极强，说干就干', '抗压能力好，擅长高负荷运转', '在奔波中找到意义感'],
    weaknesses: ['停不下来，难以休息', '有时忙着忙着忘了方向', '身体会先于意志崩溃'],
    relationships: '你需要一个能跟上你节奏，或者愿意成为你"加油站"的伴侣。',
    career: '销售、运营、创业、旅行相关……所有能动起来、看到结果的工作都让你如鱼得水。',
    growth: '给自己安排一个什么都不做的下午——不是休息，是练习和自己待在一起。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-drnk', testId: 'test-sbti', typeCode: 'DRNK',
    typeName: '酒鬼',
    summary: '借酒解压，清醒就焦虑，情绪靠酒精平复',
    description: '你在清醒状态下背负着太多，而酒精是那个帮你卸下盔甲的东西。微醺的你更真实、更放松、更像你自己。你不是酗酒，你只是需要一个出口——只是你目前选的这个出口是液体的。',
    strengths: ['真实，不加掩饰', '社交时很有感染力', '对生活有强烈的感受力'],
    weaknesses: ['情绪依赖外部工具调节', '清醒时的焦虑是根本问题', '长期对身体不友好'],
    relationships: '你需要一个让你在清醒状态下也觉得安全的人——那才是真正的解压。',
    career: '创意、表演、文字……感受力强的你在需要情感输出的领域能创作出真实打动人的东西。',
    growth: '下次想开酒之前，先给自己5分钟，问问：我现在真正需要的是什么？',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-woc', testId: 'test-sbti', typeCode: 'WOC',
    typeName: '握草人',
    summary: '一惊一乍，吃瓜前线，情绪全写脸上',
    description: '你是世界上最诚实的人之一——因为你根本不会隐藏情绪。你的脸是一个实时弹幕屏，任何事情发生，你的"卧槽/握草/哦我去"都会第一时间出现。你活得很真实，也很有活力。',
    strengths: ['情绪真实、感染力强', '第一时间捕捉到有趣的事', '让身边人觉得有趣'],
    weaknesses: ['有时反应过激', '可能让不了解你的人感到累', '容易被情绪带着走'],
    relationships: '你需要一个不怕你"激"的人，以及偶尔能帮你降降温的伴侣。',
    career: '内容、直播、评论、采编……你的真实反应就是内容本身。',
    growth: '下次在"握草"之前，给自己3秒，看看这件事值不值得消耗你这么多能量。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-hhhh', testId: 'test-sbti', typeCode: 'HHHH',
    typeName: '傻乐者',
    summary: '没心没肺，爱笑乐观，烦恼少、易满足',
    description: '你是稀缺物种。你不是没有问题，你只是莫名觉得问题没那么严重。你笑点低，满足感高，别人觉得烦的事你觉得还好，别人觉得无聊的事你觉得挺有趣。你天生自带"轻"的质感。',
    strengths: ['极强的韧性和恢复力', '不容易陷入负面情绪', '带给身边人轻松感'],
    weaknesses: ['有时对严肃问题反应不足', '可能被认为"不靠谱"或"不认真"', '偶尔会在需要共情时显得冷漠'],
    relationships: '你是最好相处的伴侣之一，只要对方能接受你在他们最崩溃的时候笑出来。',
    career: '任何需要维持正向氛围的岗位都适合你：用户运营、品牌、儿童教育……',
    growth: '试着在一件事上真正"认真"一次，不是为了结果，而是感受一下专注的感觉。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-lovr', testId: 'test-sbti', typeCode: 'LOVR',
    typeName: '多情者',
    summary: '爱意太满，容易动心，真诚却总受伤',
    description: '你的爱意是真实的，真实到有时候让你自己都害怕。你很容易动心，很容易全情投入，也很容易在对方没有相同反应时独自落空。你不需要"修好"这份情感，只需要找到同样有勇气去爱的人。',
    strengths: ['深情，真诚', '高度共情，善于理解他人', '敢于先付出'],
    weaknesses: ['容易受伤', '有时爱意浓度高到让对方有压力', '反复受伤后可能走向另一个极端'],
    relationships: '你需要的不是完美的人，而是一个同样愿意主动的人。',
    career: '教育、创作、心理咨询……需要真情感投入的工作，你能做出最感动人的东西。',
    growth: '在下次全情投入之前，问自己一句：对方有没有同样程度地在乎我？',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-eat', testId: 'test-sbti', typeCode: 'EAT',
    typeName: '干饭人',
    summary: '美食至上，干饭第一，靠吃治愈一切',
    description: '你是真正的美食信徒。难过了？吃。高兴了？吃。无聊了？想吃什么。你的人生大事有很大一部分都和食物有关——下顿吃什么，和谁吃，去哪吃。食物是你最稳定的情绪锚点。',
    strengths: ['幸福感来源稳定', '对生活的热情总能通过吃找回来', '是聚餐的灵魂人物'],
    weaknesses: ['有时用吃来回避情绪', '钱包……你懂的', '选不出来吃什么的时候比任何事都痛苦'],
    relationships: '最好找一个同样爱吃的人，一起探店就是最好的约会。',
    career: '美食博主、餐饮、食品研发……或者你只要找到一个离好吃的地方近的公司就满足了。',
    growth: '下次在情绪低落时，先问问自己真正需要的是什么——不一定是食物，但食物也没问题。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-thank', testId: 'test-sbti', typeCode: 'THANK',
    typeName: '感恩者',
    summary: '别人对自己好一点就记很久，心软记恩',
    description: '你是一个轻易被善意感动的人。别人帮你一个小忙，你可能记上半年；一句温柔的话，能让你暖好几天。你不觉得这是软弱——这是真实的感受力。你比很多人都懂得珍惜。',
    strengths: ['高度感受力，懂得珍惜', '在关系里真诚温柔', '容易被打动，也容易打动别人'],
    weaknesses: ['有时付出远大于回报', '容易被感动而降低判断力', '对"无情"的人很难理解'],
    relationships: '你是最好的伴侣候选之一。只是，记得观察对方是不是同样用心在对待你。',
    career: '教育、社工、NGO、客服……所有需要真心连结的工作，你都能做出温度。',
    growth: '今天，把那份感谢说出来——无论是对某人，还是对今天还不错的天气。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-poor', testId: 'test-sbti', typeCode: 'POOR',
    typeName: '贫穷者',
    summary: '钱包空空，精神富有，永远在吃土',
    description: '你的精神状态和钱包状态形成了鲜明对比：精神上富足甚至溢出，但钱包总是莫名其妙地比你想象中扁。你不是不努力，你只是很擅长把钱花在"值得的地方"——只是那个地方往往不是银行账户。',
    strengths: ['对物质的执念低，活得轻松', '懂得享受当下', '非常擅长用最少的钱获得最大的快乐'],
    weaknesses: ['财务规划能力堪忧', '有时因为穷焦虑', '面对"你怎么还不存钱"的质问无力回答'],
    relationships: '你需要一个不在意钱包的人，或者一个能帮你存钱的人——二选一。',
    career: '你擅长在资源有限的情况下创造价值。创业、创意、独立工作者……都是可能的路。',
    growth: '今天记录一下自己花了多少钱。不是为了控制，只是先看清楚。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-ohno', testId: 'test-sbti', typeCode: 'OHNO',
    typeName: '哦不人',
    summary: '自带倒霉buff，遇事第一反应"完了"',
    description: '你不是真的比别人倒霉，你只是对"可能出问题"的感知度极高。任何事情还没发生，你已经把坏的可能性预判了个遍，然后有时候它真的发生了——"我就说嘛！"这既是你的诅咒，也是你的超能力。',
    strengths: ['风险意识极强', '在灾难真的来临时比别人镇定（因为你已经预演过了）', '谨慎不冒进'],
    weaknesses: ['先被自己的预想吓到', '好事还没到就先担心', '有时把焦虑传染给身边人'],
    relationships: '你需要一个能帮你"那应该不会这么倒霉"的人，而不是和你一起崩溃的人。',
    career: '风险管理、审计、质检……所有需要"先想到最坏情况"的工作，你是天生的人才。',
    growth: '下次"哦不"之后，想一想：如果它真的发生了，我最可能怎么应对？你会发现自己比你以为的更能搞定。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-monk', testId: 'test-sbti', typeCode: 'MONK',
    typeName: '僧人',
    summary: '四大皆空，无欲无求，看破红尘',
    description: '你活在一种淡然里。不是因为看不透，恰恰相反，是因为看得太透了——看透了之后，发现大多数事情其实不值得那么大动干戈。你不冷漠，只是你的情绪频率和世界的噪音不在一个频段。',
    strengths: ['内心平静，极难被外界干扰', '不争不抢，自有格局', '在混乱中是最稳定的存在'],
    weaknesses: ['有时被认为"格格不入"或"没人情味"', '在需要激情和热情的场合很难配合', '和执着于世俗目标的人容易产生隔阂'],
    relationships: '你需要一个同样安静的人，或者一个愿意跟着你慢下来的人。',
    career: '研究、艺术、写作、独立工作……给你一个人的空间，你能做出很深的东西。',
    growth: '找一件你愿意"在乎"的小事，让自己感受一下"执着"是什么感觉。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-atm', testId: 'test-sbti', typeCode: 'ATM',
    typeName: '送钱者',
    summary: '人形提款机，只出不进，总在吃亏',
    description: '你的善良和大方是真实的，但结果是：你总是那个"借钱不还的朋友"的提款机，那个"不好意思拒绝"的人，那个最后发现自己付了全单的人。你不是笨，你只是把别人看得比自己重。',
    strengths: ['真诚慷慨，无私', '被信任、被依赖的能力强', '在需要的时候永远到场'],
    weaknesses: ['边界感弱，容易被消耗', '难以开口说不', '反复吃亏后积累的委屈不知道往哪放'],
    relationships: '你需要一个会主动说"这次我来"的伴侣，而不是一个习惯接受你付出的人。',
    career: '适合有价值对等的工作环境，学会在职场里把自己的付出清晰定价。',
    growth: '今天练习说一次"不"——不加解释，不加道歉。就这一个字。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-thin', testId: 'test-sbti', typeCode: 'THIN',
    typeName: '思考者',
    summary: '想太多内耗王者，一件事复盘八百遍',
    description: '你的大脑永远在线，从不下班。一句话说出去了，你能在接下来的三天里分析它的每一种可能的解读方式。你不是在自寻烦恼，你只是有一个超高性能的"人际关系处理器"，只是它耗电量太大。',
    strengths: ['思维深度，洞察力强', '善于发现别人忽视的细节', '做决定前已经想得很周全'],
    weaknesses: ['停不下来，睡眠质量差', '把小事想成大事', '有时想了很久却什么都没做'],
    relationships: '你需要一个让你觉得"不需要想那么多"的人——一种让你放松的存在。',
    career: '研究、分析、策划、咨询……你的脑子就是你最好的工具。',
    growth: '试着做一件不需要"想通了再做"的事：先做，再复盘。',
    minScore: 0, maxScore: 100,
  },
  {
    id: 'sb-luck', testId: 'test-sbti', typeCode: 'LUCK',
    typeName: '幸运者',
    summary: '运气飘忽，时好时坏，天选或倒霉',
    description: '你的运气就像一枚硬币，永远不知道哪面朝上。有时你会在不经意间得到意外之喜，有时又会在最不该倒霉的时候踩到那个坑。你活在一种"不确定性"里，但你已经习惯了——甚至觉得这挺有趣的。',
    strengths: ['接受不确定性的能力强', '不会把运气当理所当然', '在好运来临时充分享受'],
    weaknesses: ['很难预测和规划', '有时被"也许会好"拖住了该行动的时机', '对运气的依赖偶尔让努力打折扣'],
    relationships: '你需要一个能在你倒霉时陪你笑的人，而不是一个怪你"怎么又这样"的人。',
    career: '创意、自由职业、投资……接受高不确定性的领域，你反而游刃有余。',
    growth: '下次"运气不好"时，问自己：除了运气，我有没有什么可以改变的地方？',
    minScore: 0, maxScore: 100,
  },
];

export function calculateSbtiResult(answers: Record<string, string>): {
  typeCode: string;
  dimensionScores: Record<string, number>;
  result: (typeof sbtiResults)[0];
} {
  const scores: Record<string, number> = {};

  sbtiQuestions.forEach((q) => {
    const optionId = answers[q.id];
    if (!optionId) return;
    const opt = q.options.find(o => o.id === optionId);
    if (!opt) return;
    Object.entries(opt.scores).forEach(([type, score]) => {
      scores[type] = (scores[type] || 0) + (score as number);
    });
  });

  // Find the type with the highest score
  let topType = 'MALO';
  let topScore = -1;
  Object.entries(scores).forEach(([type, score]) => {
    if (score > topScore) {
      topScore = score;
      topType = type;
    }
  });

  const result = sbtiResults.find(r => r.typeCode === topType) || sbtiResults[0];
  return { typeCode: topType, dimensionScores: scores, result };
}
